package app.lumbral.backend.policy;

public enum Action {
    SITE_EDIT,
    SITE_PUBLISH,
    PRODUCT_MANAGE,
    CATEGORY_MANAGE,
    PRICING_MANAGE,
    PRODUCT_MEDIA_MANAGE,
    ORDER_VIEW,
    ORDER_MANAGE,
    REFUND_MANAGE,
    SALE_CREATE,
    SERVICE_MANAGE,
    BOOKING_MANAGE,
    PAYMENT_SETTINGS_MANAGE,
    DOMAIN_MANAGE,
    STAFF_MANAGE,
    TENANT_SETTINGS_MANAGE
}
